/* 300 Days With You — cumulative iPhone picker + reviewed batch import */
(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=s=>window.escapeHtml?window.escapeHtml(s):String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pad=n=>String(n).padStart(2,'0'),sleep=ms=>new Promise(r=>setTimeout(r,ms)),me=()=>{try{return Identity.displayName(Identity.current())}catch(e){return ''}};
const today=()=>typeof todayISO==='function'?todayISO():(()=>{const d=new Date();return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`})();
let knownPhotos=[];if(window.DB&&DB.onAllPhotos)DB.onAllPhotos(x=>knownPhotos=x||[]);
function ymd(d){return d instanceof Date&&!Number.isNaN(+d)?`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`:null}
function fdate(n){const m=String(n||'').match(/(20\d{2})[-_.]?(0[1-9]|1[0-2])[-_.]?([0-2]\d|3[01])/);return m?`${m[1]}-${m[2]}-${m[3]}`:null}
function ascii(v,o,n){let s='';for(let i=0;i<n&&o+i<v.byteLength;i++){const c=v.getUint8(o+i);if(!c)break;s+=String.fromCharCode(c)}return s}
function dstr(s){const m=String(s||'').match(/(20\d{2}):(\d{2}):(\d{2})/);return m?`${m[1]}-${m[2]}-${m[3]}`:null}
async function exifDate(file){if(!(/^image\/(jpeg|jpg)$/i.test(file.type)||/\.jpe?g$/i.test(file.name)))return null;const b=await file.slice(0,Math.min(file.size,640*1024)).arrayBuffer(),v=new DataView(b);if(v.byteLength<4||v.getUint16(0,false)!==0xffd8)return null;let p=2;while(p+4<v.byteLength){if(v.getUint8(p)!==0xff){p++;continue}const mark=v.getUint8(p+1);p+=2;if(mark===0xda||mark===0xd9)break;if(p+2>v.byteLength)break;const len=v.getUint16(p,false);if(len<2||p+len>v.byteLength)break;if(mark===0xe1&&len>=10&&ascii(v,p+2,6)==='Exif'){const base=p+8;if(base+8>v.byteLength)return null;const order=ascii(v,base,2),little=order==='II';if(!little&&order!=='MM')return null;const u16=o=>v.getUint16(o,little),u32=o=>v.getUint32(o,little),str=e=>{const type=u16(e+2),count=u32(e+4);if(type!==2||!count)return null;const off=count<=4?e+8:base+u32(e+8);if(off<0||off+count>v.byteLength)return null;return ascii(v,off,count)};const root=base+u32(base+4);if(root+2>v.byteLength)return null;const count=u16(root);let exif=null,mod=null;for(let i=0;i<count;i++){const e=root+2+i*12;if(e+12>v.byteLength)break;const tag=u16(e);if(tag===0x0132)mod=dstr(str(e))||mod;if(tag===0x8769)exif=u32(e+8)}if(exif!=null){const ep=base+exif;if(ep+2<=v.byteLength){const ec=u16(ep);for(let i=0;i<ec;i++){const e=ep+2+i*12;if(e+12>v.byteLength)break;const tag=u16(e);if(tag===0x9003||tag===0x9004){const d=dstr(str(e));if(d)return d}}}}return mod}p+=len}return null}
async function detect(file){try{const d=await exifDate(file);if(d)return{date:d,source:'촬영일(EXIF)'}}catch(_e){}const n=fdate(file.name);if(n)return{date:n,source:'파일명'};const m=file.lastModified?ymd(new Date(file.lastModified)):null;return m?{date:m,source:'파일 날짜'}:{date:today(),source:'확인 필요'}}
function dataUrl(file){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onerror=reject;fr.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('image-decode-failed'));img.onload=()=>{let w=img.naturalWidth||img.width,h=img.naturalHeight||img.height,max=1440;if(Math.max(w,h)>max){const s=max/Math.max(w,h);w=Math.round(w*s);h=Math.round(h*s)}let attempt=0;const make=()=>{const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);let q=.8,u=c.toDataURL('image/jpeg',q);while(u.length>420000&&q>.42){q-=.08;u=c.toDataURL('image/jpeg',q)}if(u.length>470000&&attempt<3){attempt++;w=Math.max(640,Math.round(w*.82));h=Math.max(640,Math.round(h*.82));return make()}resolve(u)};make()};img.src=fr.result};fr.readAsDataURL(file)})}
async function addRetry(d){let e;for(let i=0;i<3;i++){try{return await DB.addPhoto(d)}catch(x){e=x;if(i<2)await sleep(400*(i+1))}}throw e}
const MAX=150;
function openImport(){const panel=$('#uploadPanel');if(!panel)return;panel.innerHTML=`<div class="modal-top"><button class="icon-btn" data-action="close-modal">✕</button></div><div class="v3-album-modal-k">PHOTO IMPORT</div><h2 class="modal-title">사진을 모은 뒤 날짜 확인</h2><div class="v3-bulk-help"><b>사진 앱에서 여러 번 나눠 골라도 누적돼요.</b><span>예: 30장 선택 → 다시 사진 추가 → 40장 선택 → 총 70장을 한꺼번에 검토.</span><span>자동 날짜는 저장 전에 사진별로 직접 수정할 수 있어요.</span></div><div class="v5-picker-actions"><label class="btn v5-file-label">＋ 사진에서 추가<input type="file" id="v5Photos" accept="image/*" multiple hidden></label><label class="btn btn-outline v5-file-label">＋ Files/iCloud Drive 폴더<input type="file" id="v5Folder" accept="image/*" multiple webkitdirectory directory hidden></label><button class="btn btn-outline" id="v5Clear" type="button">선택 비우기</button></div><div class="v4-bulk-all-date"><input class="field" type="date" id="v5AllDate"><button class="btn btn-sm btn-outline" id="v5AllApply" type="button">모두 이 날짜로</button></div><div id="v5Status" class="section-note"></div><div id="v5Groups" class="v4-bulk-groups"></div><div id="v5Rows" class="v4-bulk-rows"></div><div class="v3-album-modal-actions"><button class="btn" id="v5Save" disabled>검토한 날짜로 저장</button></div>`;
let rows=[],urls=[];const status=$('#v5Status',panel),host=$('#v5Rows',panel),groups=$('#v5Groups',panel),save=$('#v5Save',panel);const key=f=>`${f.name}|${f.size}|${f.lastModified}`;
function cleanupRow(r){try{URL.revokeObjectURL(r.objectUrl)}catch(_e){}}
function summary(){const g={};rows.forEach(r=>(g[r.date]=g[r.date]||0)++);groups.innerHTML=Object.entries(g).sort((a,b)=>a[0].localeCompare(b[0])).map(([d,n])=>`<span><b>${esc(d)}</b> ${n}장</span>`).join('');status.textContent=`현재 ${rows.length}장 선택됨 · 최대 ${MAX}장`;save.disabled=!rows.length}
function render(){host.innerHTML=rows.map((r,i)=>`<div class="v4-bulk-row"><img src="${esc(r.objectUrl)}" alt=""><div class="v4-bulk-file"><b>${esc(r.file.name)}</b><span>${esc(r.source)}</span></div><input class="field" type="date" data-v5-date="${i}" value="${esc(r.date)}"><button class="v5-row-remove" type="button" data-v5-remove="${i}" aria-label="이 사진 제외">×</button></div>`).join('');$$('[data-v5-date]',host).forEach(x=>x.onchange=()=>{const r=rows[+x.dataset.v5Date];if(r){r.date=x.value||r.date;summary()}});$$('[data-v5-remove]',host).forEach(x=>x.onclick=()=>{const i=+x.dataset.v5Remove;if(rows[i])cleanupRow(rows[i]);rows.splice(i,1);render();summary()});summary()}
async function append(files){const existing=new Set(rows.map(r=>r.key)),incoming=Array.from(files||[]).filter(f=>f.type.startsWith('image/')||/\.(jpe?g|png|webp|heic|heif)$/i.test(f.name));let added=0,skipped=0;for(const f of incoming){const k=key(f);if(existing.has(k)){skipped++;continue}if(rows.length>=MAX){skipped++;continue}status.textContent=`날짜 확인 중 ${rows.length+1} / ${Math.min(MAX,rows.length+incoming.length)} · ${f.name}`;const info=await detect(f),objectUrl=URL.createObjectURL(f);rows.push({file:f,key:k,date:info.date,source:info.source,objectUrl});existing.add(k);added++}render();status.textContent=`${added}장 추가됨 · 현재 ${rows.length}장${skipped?` · ${skipped}장 중복/한도 제외`:''}`}
$('#v5Photos',panel).onchange=async e=>{const fs=Array.from(e.target.files||[]);e.target.value='';await append(fs)};$('#v5Folder',panel).onchange=async e=>{const fs=Array.from(e.target.files||[]);e.target.value='';await append(fs)};$('#v5Clear',panel).onclick=()=>{rows.forEach(cleanupRow);rows=[];render()};$('#v5AllApply',panel).onclick=()=>{const d=$('#v5AllDate',panel).value;if(!d)return;rows.forEach(r=>r.date=d);render()};save.onclick=async()=>{if(!rows.length)return;save.disabled=true;const reps={};knownPhotos.forEach(p=>{if(p.hero)reps[p.date]=true});const ok=[],fail=[];for(let i=0;i<rows.length;i++){const r=rows[i];status.textContent=`저장 중 ${i+1} / ${rows.length} · ${r.date}`;try{const url=await dataUrl(r.file),representative=!reps[r.date];await addRetry({date:r.date,url,hero:representative,bookPick:false,place:'',food:'',type:'',moods:[],title:'',caption:'',author:me(),originalName:r.file.name,dateSource:r.source});if(representative)reps[r.date]=true;ok.push(r)}catch(e){console.warn('[v5 photo import]',r.file.name,e);fail.push(r)}if((i+1)%10===0)await sleep(350)}const counts={};ok.forEach(r=>(counts[r.date]=counts[r.date]||0)++);for(const[d,n]of Object.entries(counts)){try{await DB.logActivity('photo',d,me(),`${n}장 추가`)}catch(_e){}}ok.forEach(cleanupRow);rows=fail;if(fail.length){render();status.innerHTML=`<b>${ok.length}장 저장 완료</b> · ${fail.length}장 실패. 실패한 사진만 남겨두었어요.`;save.disabled=false;save.textContent='실패한 사진 다시 저장'}else{status.innerHTML=`<b>${ok.length}장 저장 완료 ✓</b>`;save.textContent='저장 완료';Router.toast(`${ok.length}장의 사진을 저장했어요`);setTimeout(()=>{$('#uploadModal')?.classList.remove('is-open');document.body.classList.remove('modal-open')},700)}};$('#uploadModal').classList.add('is-open');document.body.classList.add('modal-open')}
function replace(){const b=$('#v3BulkPhotoBtn');if(!b||b.dataset.v5==='1')return;const n=b.cloneNode(true);n.dataset.v5='1';n.textContent='＋ 여러 장 · 날짜 검토';n.onclick=openImport;b.replaceWith(n)}
function prefillExistingTitle(){const input=$('#v3MetaTitle');if(!input||input.dataset.v5Ready)return;input.dataset.v5Ready='1';const img=$('.v3-meta-preview img');if(!img)return;const p=knownPhotos.find(x=>String(x.url||'')===String(img.src||''));if(p&&p.title&&!input.value)input.value=p.title}
let q=false;const mo=new MutationObserver(()=>{if(q)return;q=true;requestAnimationFrame(()=>{q=false;replace();prefillExistingTitle()})});mo.observe(document.body,{childList:true,subtree:true});replace();prefillExistingTitle();
})();

/* Load V6 after the existing V3 stack without disturbing V2. */
(function(){
  if(document.getElementById('v6DynamicCss'))return;
  const link=document.createElement('link');link.id='v6DynamicCss';link.rel='stylesheet';link.href='css/v3-fix6.css?v=12';document.head.appendChild(link);
  const files=['data/latest-chat-0812.js','data/latest-chat-0813.js','data/latest-chat-0814.js','data/latest-chat-0815.js','data/latest-chat-0816.js','data/latest-chat-0817.js','data/latest-chat-corrections.js','js/v3-fix6.js'];
  const load=src=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src+'?v=12';s.onload=resolve;s.onerror=reject;document.body.appendChild(s)});
  (async()=>{for(const f of files){try{await load(f)}catch(e){console.warn('[V6 loader]',f,e)}}})();
})();
